auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Alan's World
url: http://alankell.github.io
feed: /atom.xml
author_info: <a href="http://alankell.github.io/">Alan</a>
production_url : http://alankell.github.io
