auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Alan's World
url: http://autumnme.com
feed: /atom.xml
author_info: <a href="http://autumnme.com/">Alan</a>
production_url : http://autumnme.com